# Vagrantfile (http://www.vagrantup.com)
#=============================================================================
# This program installs Mindboggle (http://mindboggle.info) and dependencies
# in a VirtualBox environment (virtual machine) using Vagrant software.
# It calls a bash setup script as 'vagrant' (not root) to install Mindboggle.
# Vagrant (vagrantup.com) and VirtualBox (virtualbox.org) should be installed,
# and there needs to be a good Internet connection. Installing ANTs requires
# considerable (> 1 GB) RAM.
#
# See build_mindboggle_vm.sh to build a reusable box from the VirtualBox.
#
# Usage:
#     vagrant up
#
# ssh into the vm:
#     vagrant ssh
#
#
# Authors:
#     - Arno Klein, 2014-2016  (arno@mindboggle.info)  http://binarybottle.com
#
# Copyright 2016,  Mindboggle team, Apache v2.0 License
#=============================================================================

Vagrant.configure("2") do |conf|

    # Initialize with a basic Ubuntu Linux box:
    conf.vm.box = "ubuntu/trusty64"

    # Provide path to Mindboggle installation program (not as root):
    conf.vm.provision :shell do |sh|
        sh.privileged = false
        sh.path = "https://raw.githubusercontent.com/nipy/mindboggle/master/install/install_mindboggle.sh"
        #sh.path = "../install_mindboggle.sh"
    end

    # Configure number of CPUs maximum percent per CPU, and memory (MB RAM):
    conf.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--cpus", "6"]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "95"]
        vb.customize ["modifyvm", :id, "--memory", "14000"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    # Disable private key for easy ssh login:
    conf.ssh.username = "vagrant"
    conf.ssh.password = "vagrant"

end

