#!/usr/bin/python
"""
Mindboggle virtual machine setup script.

This program packages Mindboggle (http://mindboggle.info) and dependencies
in a VirtualBox virtual machine using Vagrant software.
It calls a bash setup script in the same folder: setup_mindboggle.sh,
(tested on Ubuntu 14.04 and MacOSX 10.11 x86_64 machines).
Vagrant (http://www.vagrantup.com) and VirtualBox (http://www.virtualbox.org)
must be installed, and you need a good Internet connection.
Run this program from within the directory containing it.

HELP:
-----
For help, type the following in a terminal window::

    python setup_mindboggle_vm --help

INSTALL:
--------
One-time installation for a given configuration:
Here we configure access to ANTs and FreeSurfer data via local
mounted directories, and set the number of processors to 6::

    python setup_mindboggle_vm --install \
                               --out /Users/arno/mindboggled \
                               --freesurfer /Applications/freesurfer/subjects \
                               --ants /data/antsCorticalThickness/subjects \
                               --proc 6 --mem 4096 --cpu 75
    vagrant up mindboggle

RUN MINDBOGGLE:
---------------
    vagrant up
    vagrant ssh mindboggle

MISC COMMANDS:
--------------
    VBoxManage list runningvms  # running virtual machines
    vagrant status  # status of virtual machines

------------------------------------------------------------------------------
ADVANCED: To build the above Mindboggle box from scratch::

    # Run this file in your setup directory, and build the box:
    python setup_mindboggle_vm --build --install
    vagrant up build
    VBoxManage list vms  # to find <vm name> below
    vagrant package --base <vm name> --output mindboggle.<version>.box

    # Upload the box to a website (example):
    rsync -avz --sparse -e /usr/bin/ssh mindboggle.<version>.box
        binarybottle@binarybottle.com:media.mindboggle.info/vm/

    # The --install argument downloads the above box and installs mindboggle
    # and dependencies on it.  Alternatively, you can ssh into the box:
    vagrant box add my_mindboggle mindboggle.<version>.box
    vagrant init my_mindboggle
    vagrant up
    vagrant ssh mindboggle
------------------------------------------------------------------------------

Tutorial for building a box:
https://scotch.io/tutorials/how-to-create-a-vagrant-base-box-from-an-existing-one

Authors:
     - Arno Klein, 2014-2016  (arno@mindboggle.info)  http://binarybottle.com

Copyright 2015,  Mindboggle team (http://mindboggle.info), Apache v2.0 License

"""
import os
import argparse

#=============================================================================
# Command-line arguments
#=============================================================================
parser = argparse.ArgumentParser(description="""
This program either packages Mindboggle (http://mindboggle.info) and
all of its dependencies in a virtual machine (--build) or configures the
virtual machine (--install) with mounted directories to access FreeSurfer
recon-all subject data (--freesurfer), ANTs antsCorticalThickness.sh
subject data (--ants), or additional atlases (--atlases) and an output
directory (--out). You must have Vagrant (http://www.vagrantup.com)
and VirtualBox (http://www.virtualbox.org) installed, as well as a good
Internet connection.

Ex: python setup_mindboggle_vm
    --install
    --out /Users/arno/mindboggled
    --freesurfer /Applications/freesurfer/subjects
    --ants /data/antsCorticalThickness/subjects
    --proc 6 --mem 4096 --cpu 75 """,
    formatter_class = lambda prog:
    argparse.HelpFormatter(prog, max_help_position=40))

parser.add_argument("--script",
                    help=("setup script (full path); default: "
                          "./setup_mindboggle.sh"),
                    metavar='STR')
parser.add_argument("--out",
                    help="Output directory (default: $HOME/mindboggled)",
                    metavar='STR')
parser.add_argument("--freesurfer",
                    help=("FreeSurfer subjects directory (default: "
                          "$SUBJECTS_DIR)"),
                    metavar='STR')
parser.add_argument("--ants",
                    help=("Optional directory containing "
                          "antsCorticalThickness.sh "
                          "output in individual subject directories"),
                    metavar='STR')
parser.add_argument("--atlases",
                    help="Optional directory containing additional atlases",
                    metavar='STR')
parser.add_argument("--cpu",
                    help='Maximum CPU (percent): "--cpu 50" (default)',
                    type=int, default=50, metavar='INT')
parser.add_argument("--mem",
                    help='Maximum memory (MB): "--mem 4096" (default)',
                    type=int, default=4096, metavar='INT')
parser.add_argument("--proc",
                    help='Number of processors: "--proc 1" (default)',
                    type=int, default=1, metavar='INT')
parser.add_argument("--install",
                    help=("Configure the Vagrant box; mount ANTs and "
                          "FreeSurfer data (run once before running "
                          "mindboggle for the first time)"),
                    action='store_true')
parser.add_argument("--build",
                    help="Build Vagrant box (ADVANCED)",
                    action='store_true')

args = parser.parse_args()

#=============================================================================
# Configure mount directories and variables below
#=============================================================================
mindboggle_version = "1.0"
vagrantfile_api_version = "2"
home = os.environ['HOME']

if args.out:
    out_string = 'install_config.vm.synced_folder "{0}", ' \
        '"/home/vagrant/mindboggled"'.format(args.out)
else:
    out_string = 'install_config.vm.synced_folder "{0}/mindboggled", ' \
        '"/home/vagrant/mindboggled"'.format(home)
if args.freesurfer:
    freesurfer_string = 'install_config.vm.synced_folder "{0}", ' \
        '"/home/vagrant/freesurfer/subjects"'.\
        format(args.freesurfer)
else:
    freesurfer_string = 'install_config.vm.synced_folder "{0}", ' \
        '"/home/vagrant/freesurfer/subjects"'.\
        format(os.environ['SUBJECTS_DIR'])
if args.ants:
    ants_string = 'install_config.vm.synced_folder "{0}", ' \
                  '"/home/vagrant/ants_subjects"'.format(args.ants)
else:
    ants_string = ''
if args.atlases:
    atlases_string = 'install_config.vm.synced_folder "{0}", ' \
                     '"{1}atlases"'.format(args.atlases, home)
else:
    atlases_string = ''

#=============================================================================
# Installation script to include in Vagrant file
#=============================================================================
if args.script:
    script = args.script
else:
    script = './setup_mindboggle.sh'

#=============================================================================
# Create Vagrantfile
#=============================================================================
f = open('Vagrantfile', 'w')

vagrant_file = """# Vagrantfile (http://www.vagrantup.com)

#=============================================================================
# Configure Vagrantfile
#=============================================================================
Vagrant.configure({0}) do |config|

    #-------------------------------------------------------------------------
    # Build a Vagrant base box and install software as per the above script
    #-------------------------------------------------------------------------
    config.vm.define :build do |build_config|

        # Build from an existing Vagrant virtual box:
        build_config.vm.box = "precise64"
        build_config.vm.box_url = "http://files.vagrantup.com/precise64.box"

        # Create a forwarded port mapping to allow access to a specific port
        # within the machine from a port on the host machine. In this example,
        # accessing "localhost:8080" will access port 80 on the guest machine:
        build_config.vm.network "forwarded_port", guest: 80, host: 8080,
            auto_correct: true
        build_config.vm.network :public_network

        # Execute a script within the guest machine:
        build_config.vm.provision "shell" do |s|
            s.path = "{1}"
        end

    end

    #-------------------------------------------------------------------------
    # Configure the Mindboggle Vagrant box and mount local directories
    #-------------------------------------------------------------------------
    config.vm.define :mindboggle do |install_config|

        # Build from the mindboggle.box Vagrant virtual box
        # (VirtualBox caches it so you only download once):
        install_config.vm.box = "mindboggle"
        install_config.vm.box_url = "mindboggle.{2}.box"
        #http://media.mindboggle.info/vm/mindboggle.{2}.box"
        install_config.vm.hostname = "mindboggler"

        # Create a forwarded port mapping to allow access to a specific port
        # within the machine from a port on the host machine. In this example,
        # accessing "localhost:8080" will access port 80 on the guest machine:
        install_config.vm.network "forwarded_port", guest: 80, host: 8080,
            auto_correct: true
        install_config.vm.network :public_network

        # Share additional folders to the guest VM,
        # with paths on the guest to mount the folder.
        # Ex: install_config.vm.synced_folder "../data", "/vagrant_data"
        {3}
        {4}
        {5}
        {6}

        # Configure %CPU, memory, #CPUs
        install_config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--cpuexecutioncap", "{7}"]
          vb.customize ["modifyvm", :id, "--memory", "{8}"]
          vb.customize ["modifyvm", :id, "--cpus", "{9}"]
          vb.customize ["modifyvm", :id, "--ioapic", "on"]
        end
    end
end
""".format(vagrantfile_api_version, script, mindboggle_version,
           out_string, freesurfer_string, ants_string, atlases_string,
           args.cpu, args.mem, args.proc)

#=============================================================================
# Write Vagrantfile with substitutions
#=============================================================================
f.write(vagrant_file)
f.close()
