#!/usr/bin/env python
"""
Copy tables directories generated by Mindboggle.

Run:
    $ python copy_final_tables.py ~/data-share/mindboggled --out ~/data-share/tables

Authors:
    - Arno Klein, 2014  (arno@mindboggle.info)  http://binarybottle.com

Copyright 2014,  Mindboggle team (http://mindboggle.info), Apache v2.0 License

"""
import os
import argparse

#-----------------------------------------------------------------------------
# Command-line arguments:
#-----------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="""
                    Copy tables directories generated by Mindboggle.""",
                     formatter_class = lambda prog:
                     argparse.HelpFormatter(prog, max_help_position=40))
# "positional arguments":
parser.add_argument("IN_DIR",
                    help=('directory containing mindboggle output'))
# "optional arguments":
parser.add_argument("--out",
                    help=("output directory"),
                    default='mindboggled_tables', metavar='STR')
args = parser.parse_args()
in_dir = args.IN_DIR
out = args.out

#-----------------------------------------------------------------------------
# Copy files:
#-----------------------------------------------------------------------------
if not os.path.exists(out):
    os.makedirs(out)

dirs = os.listdir(in_dir)
for dir in dirs:

    in_tables = os.path.join(in_dir, dir, 'tables')
    out_tables = os.path.join(out, dir)
    if not os.path.exists(out_tables):
        os.makedirs(out_tables)

    cmd = 'cp -R {0} {1}'.format(in_tables, out_tables)

    os.system(cmd)


#=============================================================================
# Doctests
#=============================================================================
if __name__ == "__main__":
    import doctest
    doctest.testmod()