function [lhrh all] = collectResults(lambda)

pathMain = '/Users/yrjo/yrjo_work/mindboggle2/miccai2012/data/KKI/';

lhrh = zeros(20,4);
all = zeros(40,2);
count = 1;

path = ([pathMain 'KKI2009-11']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-14']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-15']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-16']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
%path = ([pathMain 'KKI2009-17']);
%[a b c d] = analyzeResults(path,lambda);
path = ([pathMain 'KKI2009-18']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-19']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-20']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-21']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-22']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-24']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-25']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-27']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-29']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-31']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-33']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-34']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
%path = ([pathMain 'KKI2009-36']);
%[a b c d] = analyzeResults(path,lambda);
path = ([pathMain 'KKI2009-37']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-40']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-41']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;
path = ([pathMain 'KKI2009-42']);
[a b c d] = analyzeResults(path,lambda);
lhrh(count,:) = [a b c d]; count = count + 1;

disp(count);

all(1:20,1) = lhrh(:,1);
all(21:40,1) = lhrh(:,2);
all(1:20,2) = lhrh(:,3);
all(21:40,2) = lhrh(:,4);

