/* DO NOT EDIT.
 * Generated by c:\VTK\cmakebins2\bin\vtkEncodeString.exe
 * 
 * Declare the vtkHAVSVolumeMapper_k2BeginFP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_k2BeginFP_h
#define __vtkHAVSVolumeMapper_k2BeginFP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkHAVSVolumeMapper_k2BeginFP;

#endif /* #ifndef __vtkHAVSVolumeMapper_k2BeginFP_h */
