/* DO NOT EDIT.
 * Generated by c:\VTK\cmakebins2\bin\vtkEncodeString.exe
 * 
 * Declare the vtkHAVSVolumeMapper_k6EndFP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_k6EndFP_h
#define __vtkHAVSVolumeMapper_k6EndFP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkHAVSVolumeMapper_k6EndFP;

#endif /* #ifndef __vtkHAVSVolumeMapper_k6EndFP_h */
