/* DO NOT EDIT.
 * Generated by c:\VTK\cmakebins2\bin\vtkEncodeString.exe
 * 
 * Declare the vtkHAVSVolumeMapper_k2FP string.
 *
 */
#ifndef __vtkHAVSVolumeMapper_k2FP_h
#define __vtkHAVSVolumeMapper_k2FP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkHAVSVolumeMapper_k2FP;

#endif /* #ifndef __vtkHAVSVolumeMapper_k2FP_h */
