/* DO NOT EDIT.
 * Generated by c:\VTK\cmakebins2\bin\vtkEncodeString.exe
 * 
 * Declare the vtkVolumeTextureMapper3D_TwoDependentNoShadeFP string.
 *
 */
#ifndef __vtkVolumeTextureMapper3D_TwoDependentNoShadeFP_h
#define __vtkVolumeTextureMapper3D_TwoDependentNoShadeFP_h

#include "vtkSystemIncludes.h"

VTK_VOLUMERENDERING_EXPORT extern const char *vtkVolumeTextureMapper3D_TwoDependentNoShadeFP;

#endif /* #ifndef __vtkVolumeTextureMapper3D_TwoDependentNoShadeFP_h */
