# Vagrantfile (http://www.vagrantup.com)
#=============================================================================
# This program installs Mindboggle (http://mindboggle.info) and dependencies
# in a VirtualBox environment (virtual machine) using Vagrant software.
# It calls a bash setup script in the same folder: setup_mindboggle.sh.
# Vagrant (vagrantup.com) and VirtualBox (virtualbox.org) should be installed,
# and there needs to be a good Internet connection.
#
# See build_box.sh to build a reusable box from the running VirtualBox.
#
# Usage:
#     vagrant up
#
# ssh into the vm:
#     vagrant ssh
#
#
# Authors:
#     - Arno Klein, 2014-2016  (arno@mindboggle.info)  http://binarybottle.com
#
# Copyright 2016,  Mindboggle team, Apache v2.0 License
#=============================================================================

Vagrant.configure("2") do |conf|

    conf.vm.box = "hashicorp/precise64"
    conf.vm.provision "shell", path: "https://raw.githubusercontent.com/nipy/mindboggle/master/install/install_mindboggle.sh"

    # Configure %CPU, memory (MB RAM), #CPUs
    conf.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    conf.ssh.username = "vagrant"
    conf.ssh.password = "vagrant"

end

